
# 定义很多个航道
# 一个航道: 快速代码提交

# 描述航道是做什么用的
desc "快速代码合并提交"
lane :gitCode do |options|

commit = options[:commit]
tagName = options[:tagName]

# 这里面, 只能写已有action

# 3. 提交代码到远程代码仓库
#   1. git add .
git_add(path: ".")
#   2. git commit -m "xx"
git_commit(path: ".", message: commit)
#   3. git pull origin master
git_pull(repo: "origin", branchName: "master")
#   4. git push origin master
git_push(repo: "origin", branchName: "master")

end
